### ISSUE TITLE
Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".

### ISSUE THREAD

**Issue by ChristianWulf** [ChristianWulf/qa-eclipse-plugin#45]
Error message:
```
java.lang.IllegalStateException: Java Model Exception: Java Model Status [kieker.tools.eclipse.parent does not exist]
	at pmd.eclipse.plugin.PmdUIPlugin.resourceChanged(PmdUIPlugin.java:70)
```

**Comment by ChristianWulf** [comment]
Seems to be fixed.

**Comment by ChristianWulf** [comment]
```
java.lang.IllegalStateException: Java Model Exception: Java Model Status [pmd.eclipse.plugin does not exist]
	at pmd.eclipse.plugin.PmdUIPlugin.resourceChanged(PmdUIPlugin.java:71)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:289)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:152)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:374)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1469)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2253)
	at org.eclipse.core.internal.events.NotificationManager$NotifyJob.run(NotificationManager.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: Java Model Exception: Java Model Status [pmd.eclipse.plugin does not exist]
	at org.eclipse.jdt.internal.core.JavaElement.newNotPresentException(JavaElement.java:560)
	at org.eclipse.jdt.internal.core.JavaModelManager.getPerProjectInfoCheckExistence(JavaModelManager.java:2469)
	at org.eclipse.jdt.internal.core.JavaProject.getPerProjectInfo(JavaProject.java:2202)
	at org.eclipse.jdt.internal.core.JavaProject.getRawClasspath(JavaProject.java:2224)
	at pmd.eclipse.plugin.JavaUtil.getDefaultBuildOutputFolderPaths(JavaUtil.java:38)
	at pmd.eclipse.plugin.ui.visitors.ResourceDeltaFileCollector.addFileIfApplicable(ResourceDeltaFileCollector.java:86)
	at pmd.eclipse.plugin.ui.visitors.ResourceDeltaFileCollector.visit(ResourceDeltaFileCollector.java:43)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:64)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:75)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:48)
	at pmd.eclipse.plugin.PmdUIPlugin.resourceChanged(PmdUIPlugin.java:69)
	... 9 more
```
