### ISSUE TITLE
java.lang.NoClassDefFoundError: de/chw/MyCommentUtil

### ISSUE THREAD

**Issue by ChristianWulf** [ChristianWulf/qa-eclipse-plugin#66]
```
STATUS

pluginId            org.eclipse.core.jobs
pluginVersion       3.9.3.v20180115-1757
code                2
severity            4
message             An internal error occurred during: "Analysis by PMD".
fingerprint         0e0f556200ac7a4ab6131eccb0edae93

Exception:java.lang.NoClassDefFoundError: de/chw/MyCommentUtil
	 at HIDDEN.HIDDEN(HIDDEN:-1)
	 at HIDDEN.HIDDEN(HIDDEN:-1)
	 at HIDDEN.HIDDEN(HIDDEN:-1)
	 at HIDDEN.HIDDEN(HIDDEN:-1)
	 at HIDDEN.HIDDEN(HIDDEN:-1)
	 at HIDDEN.HIDDEN(HIDDEN:-1)
	 at HIDDEN.HIDDEN(HIDDEN:-1)
	 at HIDDEN.HIDDEN(HIDDEN:-1)
	 at HIDDEN.HIDDEN(HIDDEN:-1)
	 at HIDDEN.HIDDEN(HIDDEN:-1)
	 at HIDDEN.HIDDEN(HIDDEN:-1)
	 at HIDDEN.HIDDEN(HIDDEN:-1)
	 at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	 at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.lang.ClassNotFoundException: de.chw.MyCommentUtil
	 at java.net.URLClassLoader.findClass(null:-1)
	 at java.lang.ClassLoader.loadClass(null:-1)
	 at java.lang.ClassLoader.loadClass(null:-1)
	 at HIDDEN.HIDDEN(HIDDEN:-1)
	 at HIDDEN.HIDDEN(HIDDEN:-1)
	 at HIDDEN.HIDDEN(HIDDEN:-1)
	 at HIDDEN.HIDDEN(HIDDEN:-1)
	 at HIDDEN.HIDDEN(HIDDEN:-1)
	 at HIDDEN.HIDDEN(HIDDEN:-1)
	 at HIDDEN.HIDDEN(HIDDEN:-1)
	 at HIDDEN.HIDDEN(HIDDEN:-1)
	 at HIDDEN.HIDDEN(HIDDEN:-1)
	 at HIDDEN.HIDDEN(HIDDEN:-1)
	 at HIDDEN.HIDDEN(HIDDEN:-1)
	 at HIDDEN.HIDDEN(HIDDEN:-1)
	 at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	 at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

**Comment by ChristianWulf** [comment]
Should be fixed in "CustomPmdRules".

**Comment by rju** [comment]
This issue seems not to exist anymore.
